"""Случайный выбор трека: чистые части, без сети и без yt-dlp."""

from __future__ import annotations

import pytest

from bashmak.music.search import _choose_url, _source_query


def entry(**overrides):
    """Плоская запись выдачи: годная, пока её явно не испортили."""
    data = {
        "id": "abc",
        "url": "https://x/abc",
        "duration": 200,
        "title": "нормальный трек",
        "channel": "нормальный канал",
        "view_count": 5_000_000,
    }
    data.update(overrides)
    return data


def test_source_query_wraps_plain_text():
    assert _source_query("русский рок", 20) == "ytsearch20:русский рок"


@pytest.mark.parametrize(
    "url",
    [
        "https://www.youtube.com/playlist?list=PL123",
        "http://youtu.be/abc",
    ],
)
def test_source_query_keeps_links(url):
    assert _source_query(url, 20) == url


def test_choose_url_takes_the_only_good_entry():
    entries = [
        entry(url="https://x/live", is_live=True),
        # Часовой сборник: радио встало бы на нём до вечера.
        entry(url="https://x/long", duration=36000),
        entry(url="https://x/ok"),
    ]
    assert _choose_url(entries) == "https://x/ok"


def test_choose_url_skips_live_status_flag():
    entries = [entry(url="https://x/stream", live_status="is_live"), entry(url="https://x/ok")]
    assert _choose_url(entries) == "https://x/ok"


def test_choose_url_skips_recent():
    entries = [entry(url="https://x/a"), entry(url="https://x/b")]
    assert _choose_url(entries, {"https://x/a"}) == "https://x/b"


def test_choose_url_keeps_entries_without_duration():
    """Длительность в плоской выдаче есть не всегда — это не повод отсеивать."""
    assert _choose_url([entry(url="https://x/ok", duration=None)]) == "https://x/ok"


def test_choose_url_builds_link_from_id():
    """Часть экстракторов отдаёт только id, готовой ссылки в записи нет."""
    assert _choose_url([{"id": "xyz"}]) == "https://www.youtube.com/watch?v=xyz"


@pytest.mark.parametrize(
    "entries",
    [
        [],
        [entry(is_live=True)],
        [{}],
        # Ни ссылки, ни id — брать нечего.
        [{"title": "без ссылки"}],
    ],
)
def test_choose_url_returns_empty_when_nothing_fits(entries):
    assert _choose_url(entries) == ""


def test_choose_url_skips_shorts():
    """Ролик короче минуты — обрезок, а не трек."""
    assert _choose_url([entry(url="https://x/short", duration=30)]) == ""


@pytest.mark.parametrize(
    "title",
    [
        # Бразильский фонк лезет в выдачу по «phonk» плотнее всего остального.
        "BRAZILIAN PHONK MEGAMIX",
        "Automotivo Bibi Fogosa",
        "MTG FUNK BRASIL 2024",
        "Montagem Coral",
        # ИИ-генерация.
        "AI generated song about love",
        "Ai Cover — Кино",
        "Generated by AI: synthwave",
        "трек от нейросети",
        # Переливки чужого.
        "Nightcore - Numb",
        "Blinding Lights (slowed + reverb)",
        "Some Track [BASS BOOSTED]",
    ],
)
def test_choose_url_blocks_junk_by_title(title):
    assert _choose_url([entry(title=title)]) == ""


def test_choose_url_blocks_junk_by_channel():
    assert _choose_url([entry(channel="Suno AI Music")]) == ""


@pytest.mark.parametrize(
    "title",
    [
        # Узкие правила не должны съедать соседей по смыслу.
        "Земфира — Искала",
        "Funkadelic — One Nation Under a Groove",
        "Ai Otsuka — Planetarium",
        "Kordhell — Murder In My Mind",
    ],
)
def test_choose_url_keeps_normal_titles(title):
    assert _choose_url([entry(title=title, url="https://x/ok")]) == "https://x/ok"


def test_choose_url_prefers_popular():
    entries = [
        entry(url="https://x/noname", view_count=800),
        entry(url="https://x/hit", view_count=9_000_000),
    ]
    assert _choose_url(entries, min_views=1_000_000) == "https://x/hit"


def test_choose_url_falls_back_when_views_are_unknown():
    """Счётчик в плоской выдаче необязательный — без него волна не должна встать."""
    entries = [entry(url="https://x/noname", view_count=800), entry(url="https://x/maybe", view_count=None)]
    assert _choose_url(entries, min_views=1_000_000) == "https://x/maybe"


def test_choose_url_ignores_views_when_threshold_is_zero():
    assert _choose_url([entry(url="https://x/any", view_count=3)], min_views=0) == "https://x/any"
